### ISSUE TITLE
What is the license for Panel_Locker

### ISSUE THREAD

**Issue by blacklizard** [v6cl/MyDIYthings#1]
I am planning to use your Panel_Locker in one of my conversion project, may I know what is the license for this repo?

**Comment by v6cl** [comment]
I don't know much about the license, but I published it under the mit license.
-----Original Message-----
From: ***@***.***>
To: ***@***.***>;
Cc: ***@***.***>;
Sent: 2024-03-09 (토) 17:46:27 (GMT+09:00)
Subject: [v6cl/MyDIYthings] What is the license for Panel_Locker (Issue #1)

I am planning to use your Panel_Locker in one of my conversion project, may I know what is the license for this repo?

**Comment by blacklizard** [comment]
Aight.. Thats clear it up.. thanks
